### ISSUE TITLE
aider: error: argument --model: expected one argument

### ISSUE THREAD

**Issue by iamuddeshya** [mirrajabi/aider-github-action#7]
No matter how I pass the model, always getting the error that `aider: error: argument --model: expected one argument`. 

Here we can see the model is passed 
<img width="606" alt="image" src="https://github.com/user-attachments/assets/f67b8da5-d218-4397-a266-e7cb89f3d30a">
and here we can see the error
<img width="462" alt="image" src="https://github.com/user-attachments/assets/47dfe4c2-abef-475a-8f7f-3b20bb9da638">

This is my yaml
---
name: Auto-generate PR from Issues using Aider

on:
  issues:
    types: [labeled]

permissions:
  contents: write

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Create branch
        id: create_branch
        run: |
          branch_name="aider-branch-${{ github.sha }}"
          git checkout -b $branch_name
          echo "::set-output name=ref::refs/heads/$branch_name"
      
      - name: aider-chat-action
        uses: mirrajabi/aider-github-action@v1.0.1
        timeout-minutes: 10 # So that you won't accidentally burn your OpenAI credits!
        with:
          openai_api_key: ${{ secrets.openai_api_key }}
          branch: ${{ steps.create_branch.outputs.ref }}
          aider_args: '--model gpt-4-1106-preview --yes --message "${{ github.event.issue.title }}"'
 ----

**Comment by mirrajabi** [comment]
Thanks for reporting this issue @iamuddeshya ! I've found and fixed the problem. You can now use v1.0.3.

The problem was introduced in #2 which I didn't test properly.
